site_name: OCHRE Gym
site_description: The documentation of the NREL OCHRE Gymnasium.
site_url: https://nrel.github.io/ochre_gym

repo_name: NREL/ochre_gym
repo_url: https://github.com/NREL/ochre_gym

theme:
  name: material
  features:
      - navigation.sections  # Sections are included in the navigation on the left.
      - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
      - header.autohide  # header disappears as you scroll

plugins:
  - search
  - autorefs # Cross-links to headings
  - mkdocstrings:
      handlers:
          python:
            selection:
                inherited_members: true  # Allow looking up inherited methods
            rendering:
                show_root_heading: true  # actually display anything at all...
                show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                show_signature_annotations: true
                show_source: false  # don't include source code
                members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                headings_level: 4
                
nav: 
  - Home: index.md
  - Getting Started:
    - Getting Started/basics.md
    - Getting Started/stable_baselines.md
  - Buildings: Buildings.md
  - Actions: Actions.md
  - Observations: Observations.md
  - Demand Response: Demand Response.md
  - API: 
    - API/ochre_gym-reference.md
    - API/ochre_gym-env-reference.md
    - Spaces:
      - API/ochre_gym-spaces-reference.md
      - API/ochre_gym-action-space.md
      - API/ochre_gym-observation-space.md

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: ''
      toc_depth: 1-2
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
